version: '3'
services:
    nginx:
        container_name: nginx
        build:
            context: ./etc/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./www/public:/var/www/html
            - ./etc/nginx/logs/:/var/log/nginx/
            - ./etc/nginx/sites-enabled/:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
            - mysql
    php-fpm:
        container_name: php-fpm
        extra_hosts:
        - "host.docker.internal:host-gateway"
        build:
            context: ./etc/php-fpm
            dockerfile: Dockerfile
        expose:
            - "9000"
        restart: always
        volumes:
            - ./www/public:/var/www/html
            - ./etc/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./etc/php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./etc/php-fpm/tmp/xdebug.log:/tmp/xdebug.log
            - ./etc/php-fpm/conf.d/php.ini:/usr/local/etc/php/php.ini
    mysql:
        container_name: mysql
        build:
            context: ./etc/mysql
            dockerfile: Dockerfile
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
